name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          #plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_skipped: DarkOnion0, dotfiles                 # List of repositories to skip
          #plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  # Make most used languages orange and JavaScript red
          #plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage               # Additionally display total bytes size and percentage
          plugin_languages_threshold: 1%                                 # Hides all languages less than 2%
          plugin_languages_limit: 8                                      # Display up to 8 languages
          plugin_languages_sections: most-used                           # Display most used and recently used languages stats
          plugin_languages_indepth: no                                   # Get indepth stats (see documentation before enabling)
          plugin_languages_categories: programming                       # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data  # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                              # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                                # Limit recently used stats to last week
          plugin_languages_other: true
          commits_authoring: darkonion0@users.noreply.github.com         # Surnames or email addresses used to identify your commits